import { CountryList } from "../interfaces/country-list-type";

export const countryLists: Array<CountryList> = [
    {
        display: "China",
        value: "CHINA"
    }, {
        display: "India",
        value: "INDIA",
        state: [
            {
                display: "Andhra Pradesh",
                value: ""
            }, {
                display: "Arunachal Pradesh",
                value: ""
            }, {
                display: "Bihar",
                value: ""
            }, {
                display: "Chhattisgarh",
                value: ""
            }, {
                display: "Goa",
                value: ""
            }, {
                display: "Gujarat",
                value: ""
            }, {
                display: "Haryana",
                value: ""
            }, {
                display: "Himachal Pradesh",
                value: ""
            }, {
                display: "Jharkhand",
                value: ""
            }, {
                display: "Karnataka",
                value: ""
            }, {
                display: "Kerala",
                value: "",
                districts: [
                    {
                        display: "Alappuzha",
                        value: ""
                    }, {
                        display: "Ernakulam",
                        value: ""
                    }, {
                        display: "Idukki",
                        value: ""
                    }, {
                        display: "Kannur",
                        value: ""
                    }, {
                        display: "Kasaragod",
                        value: ""
                    }, {
                        display: "Kollam",
                        value: ""
                    }, {
                        display: "Kottayam",
                        value: ""
                    }, {
                        display: "Kozhikode",
                        value: ""
                    }, {
                        display: "Malappuram",
                        value: ""
                    }, {
                        display: "Palakkad",
                        value: ""
                    }, {
                        display: "Pathanamthitta",
                        value: ""
                    }, {
                        display: "Thiruvananthapuram",
                        value: ""
                    }, {
                        display: "Thrissur",
                        value: ""
                    }, {
                        display: "Wayanad",
                        value: ""
                    }
                ]
            }, {
                display: "Assam",
                value: ""
            }, {
                display: "Madhya Pradesh",
                value: ""
            }, {
                display: "Maharashtra",
                value: ""
            }, {
                display: "Manipur",
                value: ""
            }, {
                display: "Meghalaya",
                value: ""
            }, {
                display: "Mizoram",
                value: ""
            }, {
                display: "Nagaland",
                value: ""
            }, {
                display: "Odisha",
                value: ""
            }, {
                display: "Punjab",
                value: ""
            }, {
                display: "Rajasthan",
                value: ""
            }, {
                display: "Sikkim",
                value: ""
            }, {
                display: "Tamil Nadu",
                value: ""
            }, {
                display: "Telangana",
                value: ""
            }, {
                display: "Tripura",
                value: ""
            }, {
                display: "Uttarakhand",
                value: ""
            }, {
                display: "Uttar Pradesh",
                value: ""
            }, {
                display: "West Bengal",
                value: ""
            }
        ]
    }, {
        display: "United States",
        value: "US"
    }, {
        display: "Indonesia",
        value: "INDONESIA"
    }, {
        display: "Pakistan",
        value: "PAK"
    }, {
        display: "Brazil",
        value: "BRAZIL"
    }, {
        display: "Nigeria",
        value: "NIGERIA"
    }, {
        display: "Bangladesh",
        value: "BANGLADESH"
    }, {
        display: "Russia",
        value: "RUSSIA"
    }, {
        display: "Mexico",
        value: "MEXICO"
    }, {
        display: "Japan",
        value: "JAPAN"
    }, {
        display: "Ethiopia",
        value: "ETHIOPIA"
    }, {
        display: "Philippines",
        value: "PHILIPPINES"
    }, {
        display: "	Egypt",
        value: "EGYPT"
    }, {
        display: "Vietnam",
        value: "VIETNAM"
    }, {
        display: "DR Congo",
        value: "CONGO"
    }, {
        display: "Turkey",
        value: "TURKEY"
    }, {
        display: "Iran",
        value: "IRAN"
    }, {
        display: "Germany",
        value: "GERMANY"
    }, {
        display: "Thailand",
        value: "THAILAND"
    }, {
        display: "United Kingdom",
        value: "UK"
    }, {
        display: "France",
        value: "FRANCE"
    }, {
        display: "Italy",
        value: "ITALY"
    }, {
        display: "Tanzania",
        value: "TANZANIA"
    }, {
        display: "South Africa",
        value: "SOUTHAFRICA"
    }, {
        display: "Myanmar",
        value: "MYANMAR"
    }, {
        display: "Kenya",
        value: "KENYA"
    }, {
        display: "South Korea",
        value: "SOUTHKOREA"
    }, {
        display: "Colombia",
        value: "COLOMBIA"
    }, {
        display: "Spain",
        value: "SPAIN"
    }, {
        display: "Uganda",
        value: "UGANDA"
    }, {
        display: "Argentina",
        value: "ARGENTINA"
    }, {
        display: "Algeria",
        value: "ALGERIA"
    }, {
        display: "Sudan",
        value: "SUDAN"
    }, {
        display: "Ukraine",
        value: "UKRAINE"
    }, {
        display: "Iraq",
        value: "IRAQ"
    }, {
        display: "Afghanistan",
        value: "AFGHANISTAN"
    }, {
        display: "Poland",
        value: "POLAND"
    }, {
        display: "Canada",
        value: "CANADA"
    }, {
        display: "Morocco",
        value: "MOROCCO"
    }, {
        display: "Saudi Arabia",
        value: "SAUDI"
    }, {
        display: "Uzbekistan",
        value: "UZBEKISTHAN"
    }, {
        display: "Peru",
        value: "PERU"
    }, {
        display: "Angola",
        value: "ANGOLA"
    }, {
        display: "Malaysia",
        value: "MALAYSIA"
    }, {
        display: "Mozambique",
        value: "MOZAMBIQUE"
    }, {
        display: "Ghana",
        value: "GHANA"
    }, {
        display: "Yemen",
        value: "YEMEN"
    }, {
        display: "Nepal",
        value: "NEPAL"
    }, {
        display: "Venezuela",
        value: "VENEZUELA"
    }, {
        display: "Madagascar",
        value: "MADAGASCAR"
    }, {
        display: "Cameroon",
        value: "CAMEROON"
    }, {
        display: "Côte d'Ivoire",
        value: "COTEDIVOIRE"
    }, {
        display: "North Korea",
        value: "NORTHKOREA"
    }, {
        display: "Australia",
        value: "AUSTRALIA"
    }, {
        display: "Niger",
        value: "NIGER"
    }, {
        display: "Sri Lanka",
        value: "SRILANKA"
    }, {
        display: "Burkina Faso",
        value: "BURKINAFASO"
    }, {
        display: "Mali",
        value: "MALI"
    }, {
        display: "Romania",
        value: "ROMANIA"
    }, {
        display: "Malawi",
        value: "MALAWI"
    }, {
        display: "Chile",
        value: "CHILE"
    }, {
        display: "Kazakhstan",
        value: "KAZAKHSTAN"
    }, {
        display: "Zambia",
        value: "ZAMBIA"
    }, {
        display: "Guatemala",
        value: "GUATEMALA"
    }, {
        display: "Ecuador",
        value: "ECUADOR"
    }, {
        display: "Syria",
        value: "SYRIA"
    }, {
        display: "Netherlands",
        value: "NETHERLANDS"
    }, {
        display: "Senegal",
        value: "SENEGAL"
    }, {
        display: "Cambodia",
        value: "CAMBODIA"
    }, {
        display: "Chad",
        value: "CHAD"
    }, {
        display: "Somalia",
        value: "SOMALIA"
    }, {
        display: "Zimbabwe",
        value: "ZIMBABWE"
    }, {
        display: "Guinea",
        value: "GUINEA"
    }, {
        display: "Rwanda",
        value: "RWANDA"
    }, {
        display: "Benin",
        value: "BENIN"
    }, {
        display: "Burundi",
        value: "BURUNDI"
    }, {
        display: "Tunisia",
        value: "TUNISIA"
    }, {
        display: "Bolivia",
        value: "BOLIVIA"
    }, {
        display: "Belgium",
        value: "BELGIUM"
    }, {
        display: "Haiti",
        value: "HAITI"
    }, {
        display: "Cuba",
        value: "CUBA"
    }, {
        display: "South Sudan",
        value: "SOUTHSUDAN"
    }, {
        display: "Dominican Republic",
        value: "DEOMINICANREPUBLIC"
    }, {
        display: "Czech Republic (Czechia)",
        value: "CZECHIA"
    }, {
        display: "Greece",
        value: "GREECE"
    }, {
        display: "Jordan",
        value: "JORDAN"
    }, {
        display: "Portugal",
        value: "PROTUGAL"
    }, {
        display: "Azerbaijan",
        value: "AZERBAIJAN"
    }, {
        display: "Sweden",
        value: "SWEDEN"
    }, {
        display: "Honduras",
        value: "HONDURAS"
    }, {
        display: "United Arab Emirates",
        value: "UAE"
    }, {
        display: "Hungary",
        value: "HUNGARY"
    }, {
        display: "Tajikistan",
        value: "TAJIKISTHAN"
    }, {
        display: "Belarus",
        value: "BELARUS"
    }, {
        display: "Austria",
        value: "AUSTRIA"
    }, {
        display: "Papua New Guinea",
        value: "PAPUANEWGUIENA"
    }, {
        display: "Serbia",
        value: "SERBIA"
    }, {
        display: "Israel",
        value: "ISRAEL"
    }, {
        display: "Switzerland",
        value: "SWITZERLAND"
    }, {
        display: "Togo",
        value: "TOGO"
    }, {
        display: "Sierra Leone",
        value: "SIERRALEONE"
    }, {
        display: "Laos",
        value: "LAOS"
    }, {
        display: "Paraguay",
        value: "PARAGUAY"
    }, {
        display: "Bulgaria",
        value: "BULGARIA"
    }, {
        display: "Libya",
        value: "LIBYA"
    }, {
        display: "Lebanon",
        value: "LEBANON"
    }, {
        display: "Nicaragua",
        value: "NICARAGUA"
    }, {
        display: "Kyrgyzstan",
        value: "KYRGYZSTAN"
    }, {
        display: "El Salvador",
        value: "ELSALVADOR"
    }, {
        display: "Turkmenistan",
        value: "TURKMENISTAN"
    }, {
        display: "Singapore",
        value: "SINGAPORE"
    }, {
        display: "Denmark",
        value: "DENMARK"
    }, {
        display: "Finland",
        value: "FINLAND"
    }, {
        display: "Congo",
        value: "CONGO"
    }, {
        display: "Slovakia",
        value: "SLOVAKIA"
    }, {
        display: "Norway",
        value: "NORWAY"
    }, {
        display: "Oman",
        value: "OMAN"
    }, {
        display: "State of Palestine",
        value: "PALESTINE"
    }, {
        display: "Costa Rica",
        value: "COSTARICA"
    }, {
        display: "Liberia",
        value: "LIBERIA"
    }, {
        display: "Ireland",
        value: "IRELAND"
    }, {
        display: "Central African Republic",
        value: "AFRICANRE"
    }, {
        display: "New Zealand",
        value: "NEWZEALAND"
    }, {
        display: "Mauritania",
        value: "MAURITANIA"
    }, {
        display: "Panama",
        value: "PANAMA"
    }, {
        display: "Kuwait",
        value: "KUWAIT"
    }, {
        display: "Croatia",
        value: "CROATIA"
    }, {
        display: "Moldova",
        value: "MOLDOVA"
    }, {
        display: "Georgia",
        value: "GEORGIA"
    }, {
        display: "Eritrea",
        value: "ERITERA"
    }, {
        display: "Uruguay",
        value: "URUGUAY"
    }, {
        display: "Bosnia and Herzegovina",
        value: "BOSNIAHERZEGOVINA"
    }, {
        display: "Mongolia",
        value: "MONGOLIA"
    }, {
        display: "Armenia",
        value: "ARMENIA"
    }, {
        display: "Jamaica",
        value: "JAMAICA"
    }, {
        display: "Qatar",
        value: "QATAR"
    }, {
        display: "Albania",
        value: "ALBANIA"
    }, {
        display: "Lithuania",
        value: "LITHUANIA"
    }, {
        display: "Namibia",
        value: "NAMIBIA"
    }, {
        display: "Gambia",
        value: "GAMBIA"
    }, {
        display: "Botswana",
        value: "BOTSWANA"
    }, {
        display: "Gabon",
        value: "GABON"
    }, {
        display: "Lesotho",
        value: "LESOTHO"
    }, {
        display: "North Macedonia",
        value: "NORTHMACEDONIA"
    }, {
        display: "Slovenia",
        value: "SLOVENIA"
    }, {
        display: "Guinea-Bissau",
        value: "GUINEABISSAU"
    }, {
        display: "Latvia",
        value: "LATVIA"
    }, {
        display: "Bahrain",
        value: "BAHRAIN"
    }, {
        display: "Equatorial Guinea",
        value: "EQUATORIALGUINEA"
    }, {
        display: "Trinidad and Tobago",
        value: "TRINIDADTOBAGO"
    }, {
        display: "Estonia",
        value: "ESTONIA"
    }, {
        display: "Timor-Leste",
        value: "TIMORLESTE"
    }, {
        display: "Mauritius",
        value: "MAURITIUS"
    }, {
        display: "Cyprus",
        value: "CYPRUS"
    }, {
        display: "Eswatini",
        value: "ESWATINI"
    }, {
        display: "Djibouti",
        value: "DJIBOUTI"
    }, {
        display: "Fiji",
        value: "FIJI"
    }, {
        display: "Comoros",
        value: "COMOROS"
    }, {
        display: "Guyana",
        value: "GUYANA"
    }, {
        display: "Bhutan",
        value: "BHUTAN"
    }, {
        display: "Solomon Islands",
        value: "SOLOMONISLANDS"
    }, {
        display: "Montenegro",
        value: "MONTENEGRO"
    }, {
        display: "Luxembourg",
        value: "LUXEMBOURG"
    }, {
        display: "Suriname",
        value: "SURINAME"
    }, {
        display: "Cabo Verde",
        value: "CABOVERDE"
    }, {
        display: "Micronesia",
        value: "MICRONESIA"
    }, {
        display: "Maldives",
        value: "MALDIVES"
    }, {
        display: "Malta",
        value: "MALTA"
    }, {
        display: "Brunei",
        value: "BRUNEI"
    }, {
        display: "Belize",
        value: "BELIZE"
    }, {
        display: "Bahamas",
        value: "BAHAMAS"
    }, {
        display: "Iceland",
        value: "ICELAND"
    }, {
        display: "Vanuatu",
        value: "VANUATU"
    }, {
        display: "Barbados",
        value: "BARBADOS"
    }, {
        display: "Sao Tome & Principe",
        value: "SAOTOME"
    }, {
        display: "Samoa",
        value: "SAMOA"
    }, {
        display: "Saint Lucia",
        value: "SAINTLUCIA"
    }, {
        display: "Kiribati",
        value: "KIRIBATI"
    }, {
        display: "Grenada",
        value: "GRENADA"
    }, {
        display: "St. Vincent & Grenadines",
        value: "VINCENTGRENADINES"
    }, {
        display: "Tonga",
        value: "TONGA"
    }, {
        display: "Seychelles",
        value: "SEYCHELLES"
    }, {
        display: "Antigua and Barbuda",
        value: "ANTIGUABARBUDA"
    }, {
        display: "Andorra",
        value: "ANDORRA"
    }, {
        display: "Dominica",
        value: "DOMINICA"
    }, {
        display: "Marshall Islands",
        value: "MARSHALLISLANDS"
    }, {
        display: "Monaco",
        value: "MONACO"
    }, {
        display: "Liechtenstein",
        value: "LIECHTENSTEIN"
    }, {
        display: "San Marino",
        value: "SANMARINO"
    }, {
        display: "Palau",
        value: "PALAU"
    }, {
        display: "Tuvalu",
        value: "TUVALU"
    }, {
        display: "Nauru",
        value: "NAURU"
    }, {
        display: "Holy See",
        value: "HOLYSEE"
    }
]