import { ServiceList } from "../interfaces/service-list-type";

export const serviceLists: Array<ServiceList> = [
    {
        serviceName: "Casualty",
        serviceDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    }, {
        serviceName: "Anesthetics",
        serviceDescription: "Quis vel eros donec ac. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Dui sapien eget mi proin sed libero. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Nec tincidunt praesent semper feugiat nibh. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Dolor magna eget est lorem ipsum dolor sit. A iaculis at erat pellentesque adipiscing commodo. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia."
    }, {
        serviceName: "Cardiology",
        serviceDescription: "Dolor sit amet consectetur adipiscing elit ut aliquam. Eu scelerisque felis imperdiet proin fermentum leo vel. Faucibus scelerisque eleifend donec pretium. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Accumsan tortor posuere ac ut consequat. Amet nisl purus in mollis nunc sed. Pretium lectus quam id leo. Duis at consectetur lorem donec massa. Quisque sagittis purus sit amet volutpat consequat. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Amet consectetur adipiscing elit ut aliquam purus sit. Odio ut enim blandit volutpat. Ac orci phasellus egestas tellus."
    }, {
        serviceName: "Geriatrics",
        serviceDescription: "Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Nibh sit amet commodo nulla facilisi. Tortor aliquam nulla facilisi cras fermentum odio. Aliquam sem et tortor consequat id. Urna id volutpat lacus laoreet. Tempor orci dapibus ultrices in iaculis. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Tincidunt ornare massa eget egestas purus viverra accumsan. Risus at ultrices mi tempus imperdiet nulla malesuada. Turpis egestas pretium aenean pharetra. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Et pharetra pharetra massa massa ultricies mi quis. Pellentesque habitant morbi tristique senectus. A cras semper auctor neque vitae tempus quam pellentesque nec. At in tellus integer feugiat scelerisque. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Lorem mollis aliquam ut porttitor leo. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Proin gravida hendrerit lectus a."
    }, {
        serviceName: "Gastroenterology",
        serviceDescription: "Maecenas pharetra convallis posuere morbi leo urna. Eros in cursus turpis massa tincidunt dui ut ornare lectus. Vitae aliquet nec ullamcorper sit amet risus. Feugiat in fermentum posuere urna nec tincidunt praesent. Faucibus purus in massa tempor nec feugiat. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Diam quam nulla porttitor massa id. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Sed id semper risus in hendrerit gravida. Quis ipsum suspendisse ultrices gravida. Non arcu risus quis varius. Feugiat in ante metus dictum. Sit amet tellus cras adipiscing."
    }, {
        serviceName: "Gynecology",
        serviceDescription: "Sit amet tellus cras adipiscing. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Risus feugiat in ante metus dictum at. Est velit egestas dui id. Sed cras ornare arcu dui vivamus arcu felis bibendum. Convallis convallis tellus id interdum. Aliquam faucibus purus in massa tempor nec feugiat nisl. Ut porttitor leo a diam sollicitudin tempor. Tempor orci eu lobortis elementum nibh. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Dis parturient montes nascetur ridiculus mus mauris vitae. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Ornare quam viverra orci sagittis eu volutpat odio facilisis. Nisl pretium fusce id velit ut tortor. Mollis nunc sed id semper risus in. Massa enim nec dui nunc mattis enim ut tellus elementum. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Pellentesque habitant morbi tristique senectus et netus."
    }, {
        serviceName: "Hematology",
        serviceDescription: "Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Tincidunt lobortis feugiat vivamus at. Aliquam ut porttitor leo a diam sollicitudin tempor. Nisl rhoncus mattis rhoncus urna. Dui ut ornare lectus sit. Consequat semper viverra nam libero. Nec tincidunt praesent semper feugiat. Congue eu consequat ac felis donec et odio pellentesque diam. Quis viverra nibh cras pulvinar mattis nunc sed. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. At tellus at urna condimentum mattis pellentesque. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Risus quis varius quam quisque. Sed augue lacus viverra vitae congue. Dolor morbi non arcu risus quis varius. Sodales neque sodales ut etiam sit. Bibendum enim facilisis gravida neque. Libero volutpat sed cras ornare arcu dui vivamus arcu felis."
    }, {
        serviceName: "Neurology",
        serviceDescription: "Etiam sit amet nisl purus in mollis nunc sed. Mauris ultrices eros in cursus turpis massa tincidunt dui. Ornare arcu dui vivamus arcu felis bibendum ut. Convallis tellus id interdum velit laoreet. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Ornare massa eget egestas purus. Imperdiet sed euismod nisi porta lorem mollis. Eu lobortis elementum nibh tellus molestie nunc non blandit. At auctor urna nunc id cursus. Odio ut sem nulla pharetra diam. Urna cursus eget nunc scelerisque. Sit amet facilisis magna etiam tempor orci. Iaculis nunc sed augue lacus viverra vitae. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Feugiat nisl pretium fusce id velit ut tortor pretium."
    }, {
        serviceName: "Oncology",
        serviceDescription: "Nec nam aliquam sem et. Sed euismod nisi porta lorem mollis. Ut sem nulla pharetra diam sit amet nisl suscipit. Morbi tincidunt ornare massa eget. Quis imperdiet massa tincidunt nunc. Massa tempor nec feugiat nisl pretium fusce id velit ut. Pellentesque eu tincidunt tortor aliquam. Elementum facilisis leo vel fringilla est ullamcorper. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Nullam non nisi est sit amet facilisis magna etiam tempor. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo."
    }, {
        serviceName: "Ophthalmology",
        serviceDescription: "Ante in nibh mauris cursus mattis molestie a iaculis at. Eleifend mi in nulla posuere sollicitudin aliquam. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Massa vitae tortor condimentum lacinia quis vel. Risus quis varius quam quisque id diam vel. Senectus et netus et malesuada fames ac. Lacus laoreet non curabitur gravida arcu. Commodo quis imperdiet massa tincidunt nunc. Faucibus vitae aliquet nec ullamcorper sit. Morbi leo urna molestie at elementum. Iaculis nunc sed augue lacus viverra vitae. Et ultrices neque ornare aenean euismod elementum nisi quis. Placerat orci nulla pellentesque dignissim. Nullam eget felis eget nunc lobortis mattis aliquam. At quis risus sed vulputate. Odio aenean sed adipiscing diam donec adipiscing. Ornare quam viverra orci sagittis eu. Porttitor lacus luctus accumsan tortor posuere ac. Sed adipiscing diam donec adipiscing tristique."
    },
]